# Generated by Django 4.1 on 2023-01-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0002_alter_product_props_img_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_props',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_tm', models.CharField(max_length=2)),
                ('purchase_img_produto', models.ImageField(upload_to='purchase_img_product')),
                ('purchase_modelo', models.CharField(max_length=20)),
                ('purchase_parcelas', models.IntegerField()),
            ],
        ),
    ]
