# Generated by Django 4.1 on 2023-01-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0003_purchase_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_props',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
