# Generated by Django 4.1 on 2023-01-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0004_purchase_props_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_props',
            name='purchase_img_produto',
            field=models.CharField(max_length=100),
        ),
    ]
