# Generated by Django 4.1 on 2023-02-01 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminstration', '0006_purchase_props_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_props',
            name='user_name',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
