# Generated by Django 4.1 on 2023-02-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0007_alter_purchase_props_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_props',
            old_name='user_name',
            new_name='user',
        ),
    ]
