# Generated by Django 4.1 on 2023-02-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0009_alter_purchase_props_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_props',
            name='user',
        ),
    ]
