# Generated by Django 4.1 on 2023-02-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0013_purchase_props_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_props',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_props',
            name='user_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
