# Generated by Django 4.1 on 2023-02-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0014_purchase_props_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_props',
            name='purchase_modelo',
            field=models.CharField(max_length=100),
        ),
    ]
