# Generated by Django 4.1 on 2023-02-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0017_alter_perfil_bairro_alter_perfil_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='status',
            field=models.CharField(choices=[('em analise', 1), ('pronto para entrega', 2)], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
