# Generated by Django 4.1 on 2023-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0018_perfil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_props',
            name='purchase_modelo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_props',
            name='purchase_preco',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='status',
            field=models.CharField(choices=[(1, 'em análise'), (2, 'pronto para entrega')], max_length=50),
        ),
    ]
