# Generated by Django 4.1.6 on 2023-02-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0020_alter_perfil_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
