# Generated by Django 4.1.6 on 2023-02-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0021_alter_perfil_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.IntegerField(max_length=14, null=True),
        ),
    ]
