# Generated by Django 4.1.6 on 2023-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0024_alter_perfil_numero_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_props',
            name='data_lançamento',
            field=models.DateField(null=True),
        ),
    ]
