# Generated by Django 4.1.6 on 2023-02-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0025_product_props_data_lançamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_props',
            name='data_lançamento',
        ),
    ]
