# Generated by Django 4.1.6 on 2023-03-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0027_product_props_data_lançamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'em análise'), (2, 'pronto para entrega'), (3, 'entregue')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product_props',
            name='data_lançamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_props',
            name='img_produto',
            field=models.ImageField(blank=True, null=True, upload_to='img_produto/'),
        ),
        migrations.AddField(
            model_name='purchase_props',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminstration.status'),
        ),
    ]
