# Generated by Django 4.1.6 on 2023-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0028_status_alter_product_props_data_lançamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='status',
            field=models.CharField(choices=[('pagamento confirmado', 'pagamento confirmado'), ('preparando produto para entrega', 'preparando produto para entrega'), ('produto em rota', 'produto em rota'), ('produto entregue', 'produto entregue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase_props',
            name='status',
            field=models.CharField(blank=True, choices=[('pagamento confirmado', 'pagamento confirmado'), ('preparando produto para entrega', 'preparando produto para entrega'), ('produto em rota', 'produto em rota'), ('produto entregue', 'produto entregue')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
