# Generated by Django 4.1.6 on 2023-03-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0029_alter_perfil_status_alter_purchase_props_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='status',
        ),
    ]
