# Generated by Django 4.1.6 on 2023-03-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0030_remove_perfil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_props',
            name='data_hora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_props',
            name='purchase_modelo_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase_props',
            name='purchase_parcelas',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase_props',
            name='quantidade',
            field=models.CharField(max_length=30),
        ),
    ]
