# Generated by Django 4.1.6 on 2023-03-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0031_purchase_props_data_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_props',
            old_name='purchase_img_produto',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='purchase_props',
            old_name='purchase_modelo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='purchase_props',
            old_name='purchase_modelo_id',
            new_name='modelo_id',
        ),
        migrations.RenameField(
            model_name='purchase_props',
            old_name='purchase_parcelas',
            new_name='parcelas',
        ),
        migrations.RenameField(
            model_name='purchase_props',
            old_name='purchase_preco',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='purchase_props',
            old_name='purchase_tm',
            new_name='tamanho',
        ),
    ]
