# Generated by Django 4.1.6 on 2023-03-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0035_alter_purchase_props_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_props',
            name='img_url',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='purchase_props',
            name='modelo',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='purchase_props',
            name='modelo_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='purchase_props',
            name='quantidade',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='purchase_props',
            name='tamanho',
            field=models.CharField(max_length=300),
        ),
    ]
